#DB
db.driver=DRIVER NAME
db.url=YOUR URL
db.username=YOUR NAME
db.password=YOUR PASSWORD
#Redis
redis.host=VALUE
redis.port=VALUE
# JWT
jwt.secret=VALUE
jwt.access-ttl-seconds=900
jwt.refresh-ttl-seconds=1209600
#Kakao
kakao.client-id=VALUE
kakao.client-secret=
kakao.redirect-uri=VALUE
# Mail
mail.host=VALUE
mail.port=VALUE
mail.username=VALUE
mail.password=VALUE
mail.from=VALUE
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.starttls.required=true
mail.smtp.ssl.trust=VALUE
mail.debug=false
mail.verify.code-ttl-seconds=300
mail.verify.verified-ttl-seconds=1800
